version: '3.7'

services:
  rest:
    build:
      context: .
      dockerfile: ./rest.Dockerfile
    image: pokedex-back:${APP_VERSION:-1.0.0}
    command: npm run dev
    volumes:
      - "./:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: